services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  snmp-collector:
    build: ./snmp-collector
    network_mode: "host" # Crucial pour contacter l'AKCP local
    depends_on:
      - influxdb

  ai-engine:
    build: ./ai-engine
    depends_on:
      - influxdb

  web-platform:
    build: ./web-platform
    ports:
      - "8000:8000"

volumes:
  influxdb_data:
