apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-nouvameq
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: Nouvameq
      defaultBucket: datacenter_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: nouvameq-pfe-admin-token-2026
